// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYF4N9YxxMZN4Agkr-9JBAkKx5_4z8Rho',
    appId: '1:274448674373:web:69c1b81c1b8af7e697fd2c',
    messagingSenderId: '274448674373',
    projectId: 'attedance-8da8a',
    authDomain: 'attedance-8da8a.firebaseapp.com',
    storageBucket: 'attedance-8da8a.appspot.com',
    measurementId: 'G-M5WGSVL9LE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUd8MfMojayhUAXG_cyuSF5QVCtSFZ25I',
    appId: '1:274448674373:android:12274f8ddd6f757497fd2c',
    messagingSenderId: '274448674373',
    projectId: 'attedance-8da8a',
    storageBucket: 'attedance-8da8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwc5g57YILQoMFQdY_j_PdHrrbBk86zVA',
    appId: '1:274448674373:ios:8c7800c4597d073797fd2c',
    messagingSenderId: '274448674373',
    projectId: 'attedance-8da8a',
    storageBucket: 'attedance-8da8a.appspot.com',
    iosClientId: '274448674373-6e0ohm1va0i7qf7qnc4g5j166bg92vbc.apps.googleusercontent.com',
    iosBundleId: 'com.example.attedancebeta',
  );
}
